ignore:
  - "kaitai/tests" # we also don't care about coverage of test code
  - "kaitai-macros/tests" # we also don't care about coverage of test code
  - "kaitai/benches" # or coverage of benchmarks
  - "kaitai-macros/benches" # or coverage of benchmarks
